before_install:
  - sudo apt-get install python-bs4
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install nose
notifications:
  email:
    recipients:
      - abusalehmdtayeen@gmail.com
    on_success: change
    on_failure: always
script:
- nosetests --verbose
